### ISSUE TITLE
Surface was abandoned

### ISSUE THREAD

**Issue by ghost** [b3lial/android-camera2-java-example#1]
Hello, how can I help you?

Can you please tell me how to solve the error XD

Thanks for the great article.
I am learning to use Camera 2API + SurfaceView to display camera previews.
Then I found your article.

If I implement your code as a reference, I get an error occurs in

```
<CameraDeviceCallback.java line 51>cameraDevice.createCaptureSession(v, csc, handler);`
```

```

E/Legacy-CameraDevice-JNI: getNativeWindow: Surface had no valid native window.
    LegacyCameraDevice_nativeDetectSurfaceDimens: Could not retrieve native window from surface.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.camera, PID: 31898
    java.lang.IllegalArgumentException: Surface was abandoned
        at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:89)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:260)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:145)
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:520)
        at com.example.camera.CameraDeviceCallback.onOpened(CameraDeviceCallback.java:51)
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:149)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6732)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
        at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:73)
        at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceSize(LegacyCameraDevice.java:606)
        at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:87)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:260) 
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:145) 
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:520) 
        at com.example.camera.CameraDeviceCallback.onOpened(CameraDeviceCallback.java:51) 
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:149) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:198) 
        at android.app.ActivityThread.main(ActivityThread.java:6732) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
I/Process: Sending signal. PID: 31898 SIG: 9

```

The method can be implemented from other classes called by
```
cameraSurface = (SurfaceView) getActivity().findViewById(R.id.surface);
        CameraManager manager = (CameraManager) getContext().getSystemService(Context.CAMERA_SERVICE);
        new CameraController(manager, cameraSurfaceView).startCameraPreview();
```

I apologize for my poor question as a programming beginner.
I'm sorry for my poor question.

**Comment by b3lial** [comment]
Please write me an Email if you have questions and dont open a github issue

**Comment by ghost** [comment]
I'm very sorry.
I am not familiar with Github, so I did not know what to do and used an issue and I don't know your email address, so I couldn't contact you.
Is it possible to delete this issue?
